[workspace]
members = [
    "utils",
    "protos",
    "contest_service",
    "evaluation_service",
    "rpctest-client",
    "rpctest-server",
    "submission_service",
    "dispatcher_service",
    "worker_service"
]
