[workspace]
members = [
    "utils",
    "protos",
    "contest_service",
    "evaluation_service",
    "admin",
    "submission_service",
    "participant",
    "dispatcher_service",
    "worker_service"
]

