version: "3.3"

services:
  contest_service_db:
    image: mongo:4.4.8 #mongo:5.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: contestdb
    # volumes:
    #   - contest_service_db_volume:/data/db
    ports:
      - 27017:27017
  contest_service:
    build:
      context: .
      dockerfile: ./contest_service/Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - contest_service_db

  evaluation_service:
    build:
      context: .
      dockerfile: ./evaluation_service/Dockerfile
    ports:
      - 50052:50051

  submission_service_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: submissionsdb
    # volumes:
      # - ./submission_service/db/init.js:/docker-entrypoint-initdb.d/init.js
      # - submission_service_db_volume:/data/db
    ports:
      - 27020:27017
  submission_service:
    build:
      context: .
      dockerfile: ./submission_service/Dockerfile
    ports:
      - 50055:50051
    depends_on:
      - submission_service_db

  participant_web_server:
    build:
      context: .
      dockerfile: ./participant/Dockerfile
    ports:
      - 8000:80


volumes:
  contest_service_db_volume:
  submission_service_db_volume: # what for?
