version: "3.3"
services:
  rpc-server:
    build:
      context: .
      dockerfile: ./rpctest-server/Dockerfile
    ports:
      - "50051:50051"
  rpc-client:
    build:
      context: .
      dockerfile: ./rpctest-client/Dockerfile
