[package]
name = "utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protos = {path="../protos"}
rand = "0.8"
chrono = "0.4"
prost-types = "0.8"
bson = "2.0.0-beta.3"
