name: CI

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
      - uses: Swatinem/rust-cache@v1
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test

          
#  code-coverage:
#    name: Code coverage
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      # the action needs a nightly toolchain with llvm-tools
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          components: llvm-tools-preview, rustfmt
#
#      # runs cargo with defaults flags, using the default `lcov` output
#      - uses: Swatinem/fucov@v1
#      
#      - uses: Swatinem/rust-cache@v1
#      
#      # afterwards, upload the report to codecov
#      - uses: codecov/codecov-action@v1
#        with:
#          directory: coverage
